spring:
  data:
    mongodb:
      database:
      uri:
      
azure:
  keyvault:
    enabled: true
    uri:
    client-id:
    client-key:
    tenant-id:
    token-acquire-timeout-seconds: 60
    refresh-interval: 1800000